{{- if .Values.mx.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-mx
  namespace: {{ .Release.Namespace }}
  labels:
    app: relay-mx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-mx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: relay-mx
    spec:
      containers:
        - name: postfix
          image: "{{ .Values.image.postfix.repository }}:{{ .Values.image.postfix.tag }}"
          imagePullPolicy: {{ .Values.image.postfix.pullPolicy }}
          ports:
            - containerPort: 25
              name: smtp
            {{- with .Values.mx.clientAddress.xclientPort }}
            - containerPort: {{ . }}
              name: xclient
            {{- end }}
            {{- with .Values.mx.clientAddress.proxyPort }}
            - containerPort: {{ . }}
              name: proxy
            {{- end }}
          env:
            - name: RELAY_TYPE
              value: mx
            - name: MAIL_DOMAIN
              value: {{ .Values.mail.domain | quote }}
            - name: MAIL_HOSTNAME
              value: {{ .Values.mail.hostname | quote }}
            - name: MAIL_MYNETWORKS
              value: {{ .Values.mail.mynetworks | quote }}
            - name: MAIL_DOMAINS
              value: {{ include "yarilo-postfix.mailDomains" . | quote }}
            - name: LMTP_HOST
              value: {{ .Values.yarilo.lmtpHost | quote }}
            - name: LMTP_PORT
              value: {{ .Values.yarilo.lmtpPort | quote }}
            - name: RSPAMD_ADDR
              value: "relay-rspamd:11332"
            {{- if .Values.mx.rblRestrictions }}
            - name: RBL_RESTRICTIONS
              value: {{ .Values.mx.rblRestrictions | quote }}
            {{- end }}
            {{- with .Values.mx.clientAddress.xclientPort }}
            - name: MX_XCLIENT_PORT
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.mx.clientAddress.xclientHosts }}
            - name: MX_XCLIENT_HOSTS
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.mx.clientAddress.proxyPort }}
            - name: MX_PROXY_PORT
              value: {{ . | quote }}
            {{- end }}
            {{- include "yarilo-postfix.mysqlEnv" .Values | nindent 12 }}
          volumeMounts:
            {{- include "yarilo-postfix.tlsMount" .Values.tls.secretName | nindent 12 }}
          resources:
            {{- toYaml .Values.resources.postfix | nindent 12 }}
      volumes:
        {{- include "yarilo-postfix.tlsVolume" .Values.tls.secretName | nindent 8 }}
{{- end }}
